// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "PhysicsActor.generated.h"
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead
//DO NOT USE THIS, PROJECT IS BUGGY AND ANY BLUEPRINT CREATED WITH THIS CLASS AUTOMATICALLY BECOMES A STATIC MESH ACTOR IF YOU CLOSE AND REOOPEN UNREAL
//USE CustomPhysicsActor.h instead

class UStaticMeshComponent;

UCLASS()
class PROJECTLAUGH_API APhysicsActor : public AActor
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	APhysicsActor();
	FVector OffsetWhenAttached;
protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	USceneComponent* SceneRoot;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UStaticMeshComponent* StaticMesh;
	


private:

public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;

};
